"""Add column charge_id to Order model

Revision ID: b285c3f642d6
Revises: 38a99f2a4621
Create Date: 2025-03-12 13:02:27.367568

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b285c3f642d6'
down_revision = '38a99f2a4621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('charge_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_unique_constraint(None, 'order', ['charge_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='unique')
    op.drop_column('order', 'charge_id')
    # ### end Alembic commands ###
